apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-vginx-deployment
  labels:
    app: app1-vginx
spec:
  replicas: 6
  selector:
    matchLabels:
      app: app1-vginx
  template:
    metadata:
      labels:
        app: app1-vginx
    spec:
      containers:
        - name: app1-vginx
          image: devopsvmr/811pm:2
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app1-vginx-loadbalancer-service
  labels:
    app: app1-vginx
spec:
  type: LoadBalancer
  selector:
    app: app1-vginx
  ports:
    - port: 8080
      targetPort: 8080
      
      

